server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
            - id: toll-service
              uri: http://localhost:55888
              predicates:
              - Method=GET
              - Path=/tollrate/{stationId}
              - Query=apicaller
  