server:
    port: 8080

spring:
    application:
        name: toll-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            - id: toll-service
              uri: lb://tollrate-service
              predicates:
              - Method=GET
              - Path=/tollrate/{stationId}
              - Query=apicaller

eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: true
        fetch-registry: true