server:
    port: 8080

spring:
    application:
        name: toll-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            - id: toll-service-v1
              uri: lb://tollrate-service
              predicates:
              - Method=GET
              - Path=/v1/tollrate/{stationId}
              filters:
              - SetPath=/tollrate/{stationId}
              - AddResponseHeader=X-Expiring-Service,please use v2
            - id: toll-service-v2
              uri: lb://tollrate-service
              predicates:
              - Method=GET
              - Path=/v2/tollrate/{stationId}
              filters:
              - SetPath=/tollrateV2/{stationId}

eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: true
        fetch-registry: true